### PR TITLE
Setup default value in property

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by mac-cain13** [comment]
All values are set in the constructor, I like this consistent approach. Don't really see an advantage of setting this value outside of the constructor.

**Comment by ovr** [comment]
@mac-cain13 

I will try to explain my opinion about it

1. Code style
As you can see the default symfony command declared properties with default value(s), without assigment in `__construct` method!

2. Optimizing
Zend Engine provides functions to declare property with default value it in one step
(more optimize)

3. If you are using a string as default value this will be an interned string (I think)

**Comment by ovr** [comment]
ping @mac-cain13

**Comment by mac-cain13** [comment]
Thanks for the effort of explaining your PR! It's really is a matter of taste.

You won't be able to measure the performance of this change and a good optimizer should be able to rewrite it to the most optimal version anyway. That's not really something that matters in this case.

With all respect, I think this change is not a significant improvement or fix for something. The proposal is equally good as the original code and I don't want to merge in trivial taste based PRs. Lets leave it there.

**Pull request closed without merging**
