### PR TITLE
Convert to PSR-4, add more default options.

### PR DESCRIPTION
**Pull request by dopesong**
Autoload changed to PSR-4, minimum PHP required now is 5.4.

Also added two options to make it more flexible. 

--pidfile=/path/to/pidfile.pid
--interval=(5s, 10m, 1h)

Also code style changed to Symfony2, fixed some mistakes in docs.

### CODE REVIEW

**Comment by dopesong** [comment]
For those who are using it with PHP 5.3 if this will be marged I think release version should be 1.3 to not break their projects.

**Comment by mac-cain13** [comment]
Thanks @dopesong for taking the time to create a PR and using this library!

A few points of feedback;
- You did run a code formatter on the `EndlessCommand.php` file, this changes all lines. Making it very hard to see what you actually did change. You should always comply to the current code formatting of a project and if you really want to change formatting; Make it a seperate PR!

- I don't really see the benefits of changing to PSR-4. It removes only removes a folder in this library, but we have to drop PHP 5.3 to make the change. Do you think PSR-4 brings us so much that we should drop those older PHP users?

- The pidfile option should be taken care of by the daemonization tool, tools like Upstart have options for pidfile that are way more reliable.

- Passing the interval as a paramater is a nice addition!

- Also fixes in code and docs are very welcome of course.

To merge this I at least need to be able to easily see what's changed. So could you create a PR without the formatting changes? Also making separate PRs for changes or at least separate commits make it easy to cherrypick changes a maintainer wants to merge. Now it's a bit of an all or nothing PR. :)

**Comment by dopesong** [comment]
Hi @mac-cain13,

PSR-4 not drops PHP 5.3, but we should, because PHP 5.3 is no longer supported:
http://php.net/eol.php

I just copy few quotes:
*What would be the benefit, to drop 5.3 support?*

>We can make the code more clearly and easier to understand. We can also use the new features to make the library more cooler 

http://www.lornajane.net/posts/2012/proof-that-php-5-4-is-twice-as-fast-as-php-5-3

There is lots of facts why 5.3 should be droped.

What about PSR-4, it just makes folder structure simplier.

What about pidfile - it's optional, so you can monitor it with monit and so on, it makes it more powerfull :)

I'm not able to create new PR, because I'm already using my fork in few our production projects.

**Comment by mac-cain13** [comment]
Once again thanks for the PR, as I said it contains some nice improvements. Sadly the formatting changes make that I can't merge this easily and see what the impact is, so I will close this, but you are welcome to create new smaller PRs for the separate improvements.

Thanks a lot for using this project and contributing to it!

**Pull request closed without merging**
