### PR TITLE
support symfony 3.0

### PR DESCRIPTION
**Pull request by sc0rp10**
tests ran ok

### CODE REVIEW

**Comment by mac-cain13** [comment]
Awesome thanks for using this and creating a PR!

I see Travis is complaining about PHP 5.4 and 5.3 because of your type signature change. Do you need to add the `callable` declaration or is this not needed perse? If not maybe you could revert that and then I can release it.

If it is needed I have to drop PHP 5.4 and 5.3 or find a workaround.

**Comment by sc0rp10** [comment]
Hey, @mac-cain13. As I see, Symfony 3.0 requires php >= 5.5.9 (https://github.com/symfony/symfony/blob/3.0/composer.json#L19) and can't be installed to container with 5.3/5.4
I don't see any other solutions except drop PHP 5.3/5.4 support, or drop symfony 3.0 support.

**Comment by mac-cain13** [comment]
Yeah, alright we should drop the older PHP versions!

**Comment by sc0rp10** [comment]
👍

**Comment by mac-cain13** [comment]
This is now in the 1.3.0 release!

**Comment by abienvenu** [comment]
1.3.0 not only drops older PHP versions, but also older Symfony versions: 2.7 and 2.8 are incompatible with the new setCode() declaration.

**Comment by mac-cain13** [comment]
Arnaud is right about the breaking changes. They should be in a 2.0 with a clear notice that it's symfony 3 only and drops PHP versions. 

I'll fix this later today. Sorry for the confusing you with not so semantic version numbers and breaking changes!

**Pull request merged**
